# Generated by Django 3.1.7 on 2021-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_num', models.IntegerField(verbose_name='상품번호')),
                ('name', models.CharField(max_length=2000, verbose_name='상품명')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('kind', models.CharField(max_length=200, verbose_name='상품 종류')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품 모음',
                'ordering': ['pd_num'],
            },
        ),
    ]
