# Generated by Django 3.1.7 on 2021-03-08 03:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'Null'), ('tall', 'Tall'), ('grande', 'Grande'), ('venti', 'Venti')], default='', max_length=8, verbose_name='사이즈'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('', 'Null'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('MD_product', 'Md'), ('frappuccino', 'Frappuccino'), ('blended', 'Blended')], default='', max_length=200, verbose_name='상품 종류'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pd_num',
            field=models.CharField(max_length=200, verbose_name='상품번호'),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pd_num', models.CharField(max_length=200, verbose_name='상품번호')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('kind', models.CharField(choices=[('', 'Null'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('MD_product', 'Md'), ('frappuccino', 'Frappuccino'), ('blended', 'Blended')], default='', max_length=200, verbose_name='상품 종류')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('size', models.CharField(blank=True, choices=[('', 'Null'), ('tall', 'Tall'), ('grande', 'Grande'), ('venti', 'Venti')], default='', max_length=8, verbose_name='사이즈')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 상품',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
