# Generated by Django 3.1.7 on 2021-04-12 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kind",
            options={"verbose_name": "상품 종류", "verbose_name_plural": "상품 종류 목록"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["pd_num"],
                "verbose_name": "상품",
                "verbose_name_plural": "상품 목록",
            },
        ),
    ]
